framework:
    messenger:
        transports:
            sync: 'sync://'

            file_upload:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: drinkmate
                        type: direct
                    queues:
                        file.upload: ~
                retry_strategy:
                    max_retries: 3
                    delay: 1
                    multiplier: 2
        routing:
            'App\Operation\Command\SyncCommandInterface': sync

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
