nelmio_api_doc:
    documentation:
        servers:
            - url: http://localhost:80
        info:
            title: DrinkMate API
            description: API for finding drinking mates
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: [ ]

    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1
