version: '3'

tasks:
  up: docker compose up --build --remove-orphans

  down: docker compose down --remove-orphans --volumes

  chown: sudo chown -R $USER:$USER .

  diff: docker compose exec php sh -c "php bin/console doctrine:migrations:diff"

  migrate: docker compose exec php sh -c "php bin/console doctrine:migrations:migrate"

  sh: "docker compose exec php sh"

  jwt: docker compose exec php sh -c "bin/console lexik:jwt:generate-keypair"

  test_env: docker compose exec php sh -c "bin/console --env=test doctrine:database:create && bin/console --env=test doctrine:schema:create"
